baseURL: "https://afnanabdul.dev/" 
title: Afnán Alabdulwahab
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Projects
          url: projects/
          weight: 2
        - name: Courses
          url: courses/
          weight: 3
        - name: Blog
          url: blog/
          weight: 4
        # - name: Tags
        #   url: tags/
        #   weight: 5

params:
    description: "I am a software engineer & data science garduate student at the University of Virginia."
    author: Afnán Alabdulwahab
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["about", "projects", "courses", "blog"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Afnán Alabdulwahab
          subtitle: "My undergraduate background is in Electrical and Computer Engineering. After that, I spent five years as a software engineer in industrial automation, then earned my master's in Data Science from the University of Virginia in May 2025. I'm now transitioning into AI safety research.

          <br><br>
          I'm currently exploring interpretability evaluation and improving the scientific rigor of how we measure and validate AI reasoning. I am drawn to work that brings causal inference and rigorous experimental design into interpretability research, subjecting existing tools and methods to the same level of scientific scrutiny we would expect in fields like epidemiology or clinical research. I am currently exploring this through the PRISM fellowship and am open to structured research programs, and collaborations that builds both technical skills and research taste in this space.
          <br><br>
          This is where I showcase my projects and share thoughts on topics I'm exploring.
          "
          imageUrl: "prof_pic.jpg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            # Commenting out buttons while working on content (About, Projects and Blog)
            - name: About
              url: about/
            - name: Projects
              url: projects/
            - name: Courses
              url: courses/
            - name: Blog
              url: blog/
            # - name: Data
            #   url: data/
            # - name: Books
            #   url: books/
            # - name: Tags
            #   url: tags/
            # - name: Blog
            #   url: https://en.wikipedia.org/wiki/Moritz-Maria_von_Igelfeld_(character)

    socialIcons:
        - name: CV
          url: "/cv.pdf"
        - name: Email
          url: mailto:hi@afnanabdul.dev
        - name: GitHub
          url: https://github.com/afnanabdul
        - name: LinkedIn
          url: https://www.linkedin.com/in/afnan-alabdulwahab
        # - name: Location
        #   url: location/
#        - name: Zoom
#          url: https://www.zoom.us/my/igelfeld
#        - name: Office Hours
#          url: officehours/
#        - name: Google Scholar
#          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
#        - name: Substack
#          url: https://pmichaillat.substack.com
#        - name: YouTube
#          url: https://www.youtube.com/@alexandermccallsmithoffici9000
#        - name: Twitter
#          url: https://twitter.com/McCallSmith

    assets:
        disableScrollBarStyle: true
        customCSS: ["css/extended/custom.css"]
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Afnán"
      icon: apple-touch-icon.png
      iconHeight: 64

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2